// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roshe/ping.proto

package pb_go

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PingRequest struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c7b7e864615817d, []int{0}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PingResponse struct {
	Echo                 string   `protobuf:"bytes,1,opt,name=echo,proto3" json:"echo,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Env                  string   `protobuf:"bytes,3,opt,name=env,proto3" json:"env,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c7b7e864615817d, []int{1}
}

func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func (m *PingResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PingResponse) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func (m *PingResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "grpc.proto.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "grpc.proto.PingResponse")
}

func init() {
	proto.RegisterFile("roshe/ping.proto", fileDescriptor_4c7b7e864615817d)
}

var fileDescriptor_4c7b7e864615817d = []byte{
	// 195 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0x31, 0x4b, 0xc7, 0x30,
	0x14, 0xc4, 0x89, 0x29, 0x6a, 0x9f, 0x0e, 0x25, 0x8b, 0x41, 0x1c, 0x4a, 0x17, 0x3b, 0x45, 0xd0,
	0xc9, 0x55, 0x11, 0xd7, 0x92, 0xd1, 0xad, 0x96, 0x47, 0x1a, 0xb0, 0x49, 0xcc, 0x8b, 0xfd, 0xfc,
	0xd2, 0xa4, 0x52, 0xe1, 0x3f, 0xe5, 0x2e, 0x77, 0x8f, 0xfb, 0x41, 0x13, 0x3d, 0xcd, 0xf8, 0x10,
	0xac, 0x33, 0x2a, 0x44, 0x9f, 0xbc, 0x00, 0x13, 0xc3, 0x54, 0x74, 0x77, 0x0f, 0x57, 0x83, 0x75,
	0x46, 0xe3, 0xf7, 0x0f, 0x52, 0x12, 0x12, 0x2e, 0x16, 0x24, 0x1a, 0x0d, 0x4a, 0xd6, 0xb2, 0xbe,
	0xd6, 0x7f, 0xb6, 0xfb, 0x82, 0xeb, 0x52, 0xa4, 0xe0, 0x1d, 0xa1, 0x10, 0x50, 0xe1, 0x34, 0xfb,
	0xbd, 0x96, 0xb5, 0xb8, 0x83, 0x3a, 0xd9, 0x05, 0x29, 0x8d, 0x4b, 0x90, 0x67, 0x2d, 0xeb, 0xb9,
	0x3e, 0x3e, 0x44, 0x03, 0x1c, 0xdd, 0x2a, 0x79, 0x3e, 0xd8, 0xe4, 0xb6, 0xb6, 0x62, 0x24, 0xeb,
	0x9d, 0xac, 0xca, 0xda, 0x6e, 0x1f, 0xdf, 0xe0, 0xf2, 0x5d, 0x0f, 0xaf, 0xdb, 0xa2, 0x78, 0x86,
	0x2a, 0xbf, 0x37, 0xea, 0xe0, 0x56, 0xff, 0xa0, 0x6f, 0xe5, 0x69, 0x50, 0x20, 0x5f, 0xf8, 0x07,
	0x53, 0x9f, 0xe7, 0x39, 0x78, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x85, 0xe6, 0x19, 0x5e, 0x09,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GRPCPingClient is the client API for GRPCPing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GRPCPingClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type gRPCPingClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCPingClient(cc grpc.ClientConnInterface) GRPCPingClient {
	return &gRPCPingClient{cc}
}

func (c *gRPCPingClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/grpc.proto.GRPCPing/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCPingServer is the server API for GRPCPing service.
type GRPCPingServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedGRPCPingServer can be embedded to have forward compatible implementations.
type UnimplementedGRPCPingServer struct {
}

func (*UnimplementedGRPCPingServer) Ping(ctx context.Context, req *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

func RegisterGRPCPingServer(s *grpc.Server, srv GRPCPingServer) {
	s.RegisterService(&_GRPCPing_serviceDesc, srv)
}

func _GRPCPing_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCPingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.proto.GRPCPing/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCPingServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GRPCPing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.proto.GRPCPing",
	HandlerType: (*GRPCPingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GRPCPing_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roshe/ping.proto",
}
