// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GRPCPingClient is the client API for GRPCPing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCPingClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type gRPCPingClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCPingClient(cc grpc.ClientConnInterface) GRPCPingClient {
	return &gRPCPingClient{cc}
}

func (c *gRPCPingClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/GRPCPing/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCPingServer is the server API for GRPCPing service.
// All implementations must embed UnimplementedGRPCPingServer
// for forward compatibility
type GRPCPingServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedGRPCPingServer()
}

// UnimplementedGRPCPingServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCPingServer struct {
}

func (UnimplementedGRPCPingServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGRPCPingServer) mustEmbedUnimplementedGRPCPingServer() {}

// UnsafeGRPCPingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCPingServer will
// result in compilation errors.
type UnsafeGRPCPingServer interface {
	mustEmbedUnimplementedGRPCPingServer()
}

func RegisterGRPCPingServer(s grpc.ServiceRegistrar, srv GRPCPingServer) {
	s.RegisterService(&GRPCPing_ServiceDesc, srv)
}

func _GRPCPing_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCPingServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GRPCPing/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCPingServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCPing_ServiceDesc is the grpc.ServiceDesc for GRPCPing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCPing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GRPCPing",
	HandlerType: (*GRPCPingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GRPCPing_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ping.proto",
}
